version: "3"
services:
   namenode:
      image: apache/hadoop:3.3.6
      hostname: namenode
      container_name: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      volumes:
        - ./hadoop-data/namenode:/hadoop/dfs/name
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
          CLUSTER_NAME: "hadoop-cluster"
          CLUSTER_SIZE: 2
   datanode1:
      image: apache/hadoop:3.3.6
      container_name: datanode1
      command: ["hdfs", "datanode"]
      volumes:
        - ./hadoop-data/datanode1:/hadoop/dfs/data
      env_file:
        - ./config 
      environment:
          CLUSTER_NAME: "hadoop-cluster" 
          CLUSTER_SIZE: 2
      depends_on:
        - namenode
   datanode2:
      image: apache/hadoop:3.3.6
      container_name: datanode2
      command: ["hdfs", "datanode"]
      volumes:
        - ./hadoop-data/datanode2:/hadoop/dfs/data
      env_file:
        - ./config 
      environment:
          CLUSTER_NAME: "hadoop-cluster" 
          CLUSTER_SIZE: 2
      depends_on:
        - namenode
   resourcemanager:
      image: apache/hadoop:3.3.6
      hostname: resourcemanager
      container_name: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
      environment:
          CLUSTER_NAME: "hadoop-cluster"
          CLUSTER_SIZE: 2
      depends_on:
        - namenode
        - datanode1
        - datanode2
      volumes:
        - ./test.sh:/opt/test.sh
   nodemanager:
      image: apache/hadoop:3.3.6
      container_name: nodemanager
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
      environment:
          CLUSTER_NAME: "hadoop-cluster"
          CLUSTER_SIZE: 2
      depends_on:
        - namenode
        - datanode1
        - datanode2
        - resourcemanager
