version: "3"
services:
  namenode:
    image: apache/hadoop:3.3.6
    hostname: namenode
    container_name: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    volumes:
      - ./hadoop-data/namenode:/hadoop/dfs
      - ./workspace:/opt/hadoop/workspace
    env_file:
      - ./config
    environment:
      HADOOP_HOME: "/opt/hadoop"
      ENSURE_NAMENODE_DIR: "/hadoop/dfs/name"
      CLUSTER_NAME: "hadoop-cluster"
      CLUSTER_SIZE: 2
    networks: 
      - hadoop-net
  datanode1:
    image: apache/hadoop:3.3.6
    hostname: datanode1
    container_name: datanode1
    command: ["hdfs", "datanode"]
    volumes:
      - ./hadoop-data/datanode1:/hadoop/dfs
    env_file:
      - ./config
    environment:
      HADOOP_HOME: "/opt/hadoop"
      ENSURE_DATANODE_DIR: "/hadoop/dfs/data"
      CLUSTER_NAME: "hadoop-cluster" 
      CLUSTER_SIZE: 2
    networks: 
      - hadoop-net
    depends_on:
      - namenode
  datanode2:
    image: apache/hadoop:3.3.6
    hostname: datanode2
    container_name: datanode2
    command: ["hdfs", "datanode"]
    volumes:
      - ./hadoop-data/datanode2:/hadoop/dfs
    env_file:
      - ./config 
    environment:
      HADOOP_HOME: "/opt/hadoop"
      ENSURE_DATANODE_DIR: "/hadoop/dfs/data"
      CLUSTER_NAME: "hadoop-cluster" 
      CLUSTER_SIZE: 2
    networks: 
      - hadoop-net
    depends_on:
      - namenode
  resourcemanager:
    image: apache/hadoop:3.3.6
    hostname: resourcemanager
    container_name: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./config
    environment:
      HADOOP_HOME: "/opt/hadoop"
      CLUSTER_NAME: "hadoop-cluster"
      CLUSTER_SIZE: 2
    networks: 
      - hadoop-net
    depends_on:
      - namenode
      - datanode1
      - datanode2
  nodemanager:
    image: apache/hadoop:3.3.6
    hostname: nodemanager
    container_name: nodemanager
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config
    environment:
      HADOOP_HOME: "/opt/hadoop"
      CLUSTER_NAME: "hadoop-cluster"
      CLUSTER_SIZE: 2
    networks: 
      - hadoop-net
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - resourcemanager
networks: 
  hadoop-net:
    name: hadoop-net
